name: 🚀 Lint and Deploy Website
on:
    push:
      branches:
        - main
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    steps:
    - name: 🚚 Checkout code
      uses: actions/checkout@v7

    - name: ⚙️ Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: json, dom, curl, libxml, mbstring, zip, pdo, pdo_mysql
        coverage: none

    - name: 📦 Install Composer dependencies
      run: composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction

    - name: ⚙️ Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm

    - name: 📦 Install npm dependencies
      run: npm ci

    - name: 🔨 Build assets
      run: npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: ./
        server-dir: /www/
        exclude: |
          **/.git*
          **/.git*/**
          **/.github/**
          **/node_modules/**
          **/tests/**
          **/.env
          **/.env.*
          **/phpunit.xml
          **/.phpunit.cache/**
          **/vendor/**
